name: Automation flow
on:
 push:
    branches:
      - main
      - feature/*
      - bug/*
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGODB_ACCESS_URL: ${{ secrets.MONGODB_ACCESS_URL }}
      PORT: ${{ secrets.PORT }}
      JSON_PRIVATE_KEY: ${{ secrets.JSON_PRIVATE_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}
      AUTHORIZATION_CODE: ${{ secrets.AUTHORIZATION_CODE }}
      USERS_REPO_ACCESS_URL: ${{ secrets.USERS_REPO_ACCESS_URL }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test


  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    env:
      MONGODB_ACCESS_URL: ${{ secrets.MONGODB_ACCESS_URL }}
      PORT: ${{ secrets.PORT }}
      JSON_PRIVATE_KEY: ${{ secrets.JSON_PRIVATE_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}
      AUTHORIZATION_CODE: ${{ secrets.AUTHORIZATION_CODE }}
      USERS_REPO_ACCESS_URL: ${{ secrets.USERS_REPO_ACCESS_URL }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: yarn
      - name: Test and coverage
        run: npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}